### ISSUE TITLE
crash on latest version

### ISSUE THREAD

**Issue by Omarforce** [MehVahdJukaar/FarmersDelightRefabricated#104]
### Minecraft version

1.21

### Farmer's Delight version

2.2.1

### Fabric Loader version

16.9

### Fabric API version

0.106.0

### Description

crash on boot

### Steps to reproduce

trying to start server enviroment

### Mod list

![Screenshot 2024-11-08 132451](https://github.com/user-attachments/assets/70689730-227d-4e27-bfea-3b3f3c945536)

### Logs

Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'farmersdelight' at 'vectorwing.farmersdelight.FarmersDelight'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
	Suppressed: java.lang.NoClassDefFoundError: io/github/fabricators_of_create/porting_lib/loot/PortingLibLoot
		at knot/com.chefmooon.ubesdelight.common.registry.fabric.UbesDelightLootModifiersImpl.<clinit>(UbesDelightLootModifiersImpl.java:13) ~[ubesdelight-fabric-1.21-0.2.1.jar:?]
		at knot/com.chefmooon.ubesdelight.fabric.UbesDelightImpl.onInitialize(UbesDelightImpl.java:28) ~[ubesdelight-fabric-1.21-0.2.1.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
		at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
		at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
	Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.loot.PortingLibLoot
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
		... 10 more
Caused by: java.lang.NoClassDefFoundError: io/github/fabricators_of_create/porting_lib/loot/PortingLibLoot
	at knot/vectorwing.farmersdelight.common.registry.ModLootModifiers.<clinit>(ModLootModifiers.java:17) ~[FarmersDelight-1.21.1-2.2.1+refabricated.jar:?]
	at knot/vectorwing.farmersdelight.FarmersDelight.onInitialize(FarmersDelight.java:55) ~[FarmersDelight-1.21.1-2.2.1+refabricated.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.loot.PortingLibLoot
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/vectorwing.farmersdelight.common.registry.ModLootModifiers.<clinit>(ModLootModifiers.java:17) ~[FarmersDelight-1.21.1-2.2.1+refabricated.jar:?]
	at knot/vectorwing.farmersdelight.FarmersDelight.onInitialize(FarmersDelight.java:55) ~[FarmersDelight-1.21.1-2.2.1+refabricated.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	... 7 more

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by FelixAgairu** [comment]
MC
1.21.1

Farmer's Delight
2.2.1 and 2.2.0

Server crash starting after update to 2.2.1 and 2.2.0: 
[LOG](https://gist.github.com/FelixAgairu/06fd13ea069832b0a8a68690dbd5ed61)

**Comment by suerion** [comment]
Had the same Issue here on my Side

https://gist.github.com/suerion/d1e8449063bdc17c3c3ce7fb6172f7ec

**Comment by ChrysanthCow** [comment]
I think that this issue is more on Fabric Loader's cacheing. I'd suggest either deleting your .fabric folder in your game directory, or if that doesnt work, load on a fresh instance.

**Comment by ExDrill** [comment]
I also get a crash on startup, except it's on the client.
https://pastebin.com/cc7x4SFD

**Comment by ArcaneEntity** [comment]
is this fixed in the lastest 2.2.2?

**Comment by FelixAgairu** [comment]
Clean up .fabric, libraries, versions and server.jar.

MC 1.21.1
[FDR 2.2.2](https://modrinth.com/mod/farmers-delight-refabricated/version/1.21.1-2.2.2)
restart server still got this:

```
[main/WARN]: Error loading class: io/github/fabricators_of_create/porting_lib/extensions/extensions/INBTSerializableCompound (java.lang.ClassNotFoundException: io/github/fabricators_of_create/porting_lib/extensions/extensions/INBTSerializableCompound)
[main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: io/github/fabricators_of_create/porting_lib/extensions/extensions/INBTSerializableCompound
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: io/github/fabricators_of_create/porting_lib/extensions/extensions/INBTSerializableCompound
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/eu.pb4.polymer.core.impl.ImplPolymerRegistryEvent.<clinit>(ImplPolymerRegistryEvent.java:16) ~[polymer-core-0.9.18+1.21.1-659002abf83d0556.jar:?]
	at knot/net.minecraft.class_2370.handler$dna000$polymer-core$polymer$storeStatus(class_2370.java:4048) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2370.method_10272(class_2370.java:163) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_7923.method_47478(class_7923.java:242) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_7923.method_47481(class_7923.java:229) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_7923.<clinit>(class_7923.java:139) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2966.method_12851(class_2966.java:48) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.extensions.extensions.INBTSerializableCompound
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/eu.pb4.polymer.core.impl.ImplPolymerRegistryEvent.<clinit>(ImplPolymerRegistryEvent.java:16) ~[polymer-core-0.9.18+1.21.1-659002abf83d0556.jar:?]
	at knot/net.minecraft.class_2370.handler$dna000$polymer-core$polymer$storeStatus(class_2370.java:4048) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2370.method_10272(class_2370.java:163) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_7923.method_47478(class_7923.java:242) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_7923.method_47481(class_7923.java:229) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_7923.<clinit>(class_7923.java:139) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2966.method_12851(class_2966.java:48) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	... 4 more
```

**Comment by suerion** [comment]
My issue was with an clean server. I delete allways on crashes etc the server cache. 

The issue is here without the cache files

**Comment by ChrysanthCow** [comment]
I think that this is a Fabric loader issue, I'll be making a report over there, I'm just trying to replicate the bug before I send it over.

**Comment by suerion** [comment]
I will try with another profiler, or jline to give mor informations, if i could help or give mor informations, i will send it here

Thanks for your work

**Comment by MerchantPug** [comment]
Actually...

**Comment by ChrysanthCow** [comment]
@suerion May I please have your logs? I need to see if it's Porting Lib not loading or something else.

**Comment by ChrysanthCow** [comment]
Nvm, I have yours. All good

**Comment by ChrysanthCow** [comment]
Okay, so in some of your cases, Dumpling's Delight is including an old version of our Porting Lib fork.
The temporary fix is to either downgrade, or not use this addon.

I have made a new issue over on https://github.com/Joshcraft2002/Dumplings-Delight-Rewrapped/issues/5, I hope it'll get resolved soon.

**Comment by Joshcraft2002** [comment]
Hi I'll get on that right away

**Comment by suerion** [comment]
Without Dumpling Delight and Ubes Delight, It works fine
https://github.com/ChefMooon/ubes-delight/issues/30
https://github.com/Joshcraft2002/Dumplings-Delight-Rewrapped/issues/5

It is an handling issue betweend new Porting lib and older Porting Lib @MerchantPug 

Latest Log Without Ubes Delight and Dumplings Delight
https://mclo.gs/nbiYKwi

**Comment by Joshcraft2002** [comment]
dumplings delight has a new version that should fix the issue with it

**Comment by suerion** [comment]
Thanks a lot :)

**Comment by ChefMooon** [comment]
Latest version Ube's Delight also has the corrected Porting Lib dependency. Appreciate all the info to help fix it!

**Comment by suerion** [comment]
Thanks to @ChefMooon and @Joshcraft2002 server is starting now normal, 

But my Client is yet crashing with this issue 
https://mclo.gs/0ccto0n

**Comment by suerion** [comment]
@MerchantPug i think the first issues are fixed with the Updates from the other Mods, but yet i had injection errors from Mixin with porting lib

**Comment by Omarforce** [comment]
[crash-2024-11-10_00.21.57-client.txt](https://github.com/user-attachments/files/17689682/crash-2024-11-10_00.21.57-client.txt)
newest client crash report with updated mods

**Comment by Omarforce** [comment]
[crash-2024-11-10_00.21.57-client.txt](https://github.com/user-attachments/files/17689686/crash-2024-11-10_00.21.57-client.txt)

newest server crash report with updates

**Comment by suerion** [comment]
> [crash-2024-11-10_00.21.57-client.txt](https://github.com/user-attachments/files/17689686/crash-2024-11-10_00.21.57-client.txt)
> 
> 
> 
> newest server crash report with updates
> 
> 

@Omarforce did you have also an latest.log? There are more mods, they are in the crash log, like rustic delight etc

Could be, an other mod has also nested the lib.

**Comment by ChrysanthCow** [comment]
> @MerchantPug i think the first issues are fixed with the Updates from the other Mods, but yet i had injection errors from Mixin with porting lib

Ill look into this sometime later.

**Comment by ChrysanthCow** [comment]
Ive made a little explanation on this issue.
 https://github.com/MehVahdJukaar/FarmersDelightRefabricated/issues/106
